### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Fird4** [BuIlDaLiBlE/BetterHI3Launcher#65]
ERROR: Failed to download the game:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Hi3Helper.Http.Http.<InitializeMultiSession>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hi3Helper.Http.Http.<Download>d__54.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BetterHI3Launcher.MainWindow.<DownloadGameFile>d__114.MoveNext()
![Untitled](https://user-images.githubusercontent.com/125984832/220355136-55967c56-368e-4833-bd5d-913a74725fa9.png)

**Comment by BuIlDaLiBlE** [comment]
Known issue with the submodule, will be fixed in the next update.

**Comment by BuIlDaLiBlE** [comment]
Should be resolved as of [v1.4.20230329.0](https://github.com/BuIlDaLiBlE/BetterHI3Launcher/releases/tag/1.4.20230329.0). Feel free to open another issue if you encounter any more errors.
